In [42]:
import pandas as pd
import sys 
import numpy as np

In [43]:
pwd

'C:\\Users\\angie\\Documents\\Notebook_files'

In [44]:
pd.read_csv('Registro1402.csv')

,Unnamed: 0,ACUDIENTE,CIUDAD_NACIMIENTO,CIUDAD_PROCEDENCIAACADEMICA,CIUDAD_PROCEDENCIAGEOGR,CORREO,DEPARTAMENTO_PROC,DEPARTAMENTO_PROCEDE,DIRECCION_PROCEDENCIAGEOGRAFICA,ESTADOESTUDIANTE,...,PAIS_PROCEDENCIAACAD,PAIS_PROCEDENCIAGE,PERIODO,PROGRAMA,RESULTADOENTREVISTA,SEMESTRE,TELEFONO,TELEFONO_PROCED,TIPOINGRESO,DESERTOR
0,0,NaN,BARRANQUILLA,NaN,NaN,maria_sanjuan@hotmail.es,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃÂA DE SISTEMAS,NaN,8.0,3.015868e+09,NaN,ANTIGUO,1
1,1,NaN,PEDRAZA,NaN,NaN,darlisvivi2405@hotmail.com,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃÂA DE SISTEMAS,NaN,2.0,3.007364e+09,NaN,REINGRESO,1
2,2,NaN,NaN,NaN,NaN,hdiaz@acondesa.com.co,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃÂA DE SISTEMAS,NaN,9.0,3.126231e+09,NaN,ANTIGUO,1
3,3,NaN,NaN,NaN,NaN,charlye_9206@hotmail.com,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃÂA DE SISTEMAS,NaN,2.0,3.043696e+09,NaN,ANTIGUO,1
4,4,NaN,PUERTO COLOMBIA,NaN,NaN,randydariel16@gmail.com,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃÂA DE SISTEMAS,NaN,3.0,3.007948e+09,NaN,TRANSFERENCIA EXTERNA,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,221,NaN,PUERTO COLOMBIA,NaN,NaN,harrison.blanco@gmail.com,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃA DE SISTEMAS,NaN,7.0,3.007579e+09,NaN,REINGRESO,0
255,222,NaN,BARRANQUILLA,BARRANQUILLA,NaN,fac117@hotmail.com,NaN,ATLÃNTICO,NaN,MATRICULADO,...,COLOMBIA,NaN,201402.0,009 - INGENIERÃA DE SISTEMAS,NaN,6.0,3.003138e+09,NaN,ANTIGUO,0
256,223,MARTHA LUZ PEREZ OSORIO - 3685996,BARRANQUILLA,BARRANQUILLA,BARRANQUILLA,J.FONTALVO77@HOTMAIL.COM,ATLÃNTICO,ATLÃNTICO,KRA 72 # 72-35,MATRICULADO,...,COLOMBIA,COLOMBIA,201402.0,009 - INGENIERÃA DE SISTEMAS,NaN,5.0,3.008315e+09,3685996.0,ANTIGUO,0
257,224,NaN,BARRANQUILLA,NaN,NaN,gianrizzo@hotmail.com,NaN,NaN,NaN,MATRICULADO,...,NaN,NaN,201402.0,009 - INGENIERÃA DE SISTEMAS,NaN,4.0,3.015107e+09,NaN,ANTIGUO,0
258,225,ROSA ELENA MALDONADO RODRÃGUEZ - 3509464,BARRANQUILLA,BARRANQUILLA,SOLEDAD,jeisonm.1595@gmail.com,ATLÃNTICO,ATLÃNTICO,CARRERA 24B # 59B - 35,MATRICULADO,...,COLOMBIA,COLOMBIA,201402.0,009 - INGENIERÃA DE SISTEMAS,NaN,3.0,3.205854e+09,NaN,ANTIGUO,0

In [45]:
def ciudad_fix(CIUDAD):
    if CIUDAD!='BARRANQUILLA':
        return 0
    return 1

In [46]:
def estrato_fix(ESTRATO_PR):
    if ESTRATO_PR==0.0:
        return None
    return ESTRATO_PR

In [53]:
data = pd.read_csv('Registro1402.csv')

In [50]:
def transform(ruta): 
    dataframe = pd.read_csv(ruta+'.csv',encoding="latin-1")
    TotalDF = pd.DataFrame()
    TotalDF [['TIPOINGRESO','GENERO','SEMESTRE','ESTRATO_PR','ICFES_PUNTAJE','ICFES_TIPO','CIUDAD_PROCEDENCIAGEOGR', 'DESERTOR']] = dataframe[['TIPOINGRESO','GENERO','SEMESTRE','ESTRATO_PR','ICFES_PUNTAJE','ICFES_TIPO','CIUDAD_PROCEDENCIAGEOGR', 'DESERTOR']]
    TotalDF ['GENERO'] = TotalDF ['GENERO'].replace({'M':1,'F':0})
    TotalDF ['ESTRATO_PR']=TotalDF['ESTRATO_PR'].fillna(0) 
    TotalDF ['ICFES_TIPO']= TotalDF ['ICFES_TIPO'].fillna(0)
    TotalDF ['ICFES_PUNTAJE']= TotalDF ['ICFES_PUNTAJE'].fillna(0) 
    
    #ASIGNANDO A CADA CIUDAD, ---crea una nueva columna
    TotalDF['CIUDAD']=TotalDF.apply(lambda x: ciudad_fix(x['CIUDAD_PROCEDENCIAGEOGR']), axis=1);
    
    #ASIGNANDO A CADA ESTRATO, ---crea una nueva columna
    TotalDF['ESTRATO_new']=TotalDF.apply(lambda x: estrato_fix(x['ESTRATO_PR']), axis=1);
    
    #SACAR VALOR RANDOM PARA ESTRATO_NEW
    estrato_avg = TotalDF['ESTRATO_new'].mean()
    estrato_std = TotalDF['ESTRATO_new'].std()
    estrato_null_count = TotalDF['ESTRATO_new'].isnull().sum()
    estrato_null_random_list = np.random.randint(estrato_avg - estrato_std, estrato_avg + estrato_std, size=estrato_null_count)
    conValoresNulos = np.isnan(TotalDF['ESTRATO_new'])
    TotalDF.loc[np.isnan(TotalDF['ESTRATO_new']), 'ESTRATO_new'] = estrato_null_random_list
    TotalDF['ESTRATO_new'] = TotalDF['ESTRATO_new'].astype(int)
    #SACAR VALOR RANDOM PARA ESTRATO_NEW
    
    TotalDF ['ICFES_TIPO'] = TotalDF ['ICFES_TIPO'].replace({'EXAMEN TIPO 1(ANTES DEL 2000)':1,'EXAMEN TIPO 2(ANIO 2000)':2, 'EXAMEN TIPO 3(ANTES DEL 2000)':3,'EXAMEN TIPO 4 ( ANIO 2006)':4,'EXAMEN TIPO 5 (ANIO 2014)':5} )
    TotalDF ['TIPOINGRESO'] = TotalDF ['TIPOINGRESO'].replace({'ANTIGUO':1,'POR PRIMERA VEZ':2, 'REINGRESO':3,'TRANSFERENCIA EXTERNA':4,'TRANSFERENCIA INTERNA':5} )        
    [TotalDF.ESTRATO_PR,TotalDF.GENERO,TotalDF.SEMESTRE, TotalDF.TIPOINGRESO, TotalDF.CIUDAD, TotalDF.ESTRATO_new] = [TotalDF.ESTRATO_PR.astype(float),TotalDF.GENERO.astype(float),TotalDF.SEMESTRE.astype(float),TotalDF.TIPOINGRESO.astype(float),TotalDF.CIUDAD.astype(float),TotalDF.ESTRATO_new.astype(float)]
    #TotalDF [['TIPOINGRESO','GENERO','SEMESTRE','ESTRATO_new','ICFES_PUNTAJE','ICFES_TIPO','CIUDAD', 'DESERTOR']] = TotalDF[['TIPOINGRESO','GENERO','SEMESTRE','ESTRATO_new','ICFES_PUNTAJE','ICFES_TIPO','CIUDAD', 'DESERTOR']]
    #TotalDF.drop(['ESTRATO_PR','CIUDAD_PROCEDENCIAGEOGR'], axis=1)
    del TotalDF['ESTRATO_PR']
    del TotalDF['CIUDAD_PROCEDENCIAGEOGR']
    TotalDF.to_csv(ruta+"CLEANED.csv",encoding="utf-8")
    return TotalDF

In [51]:
data = transform('Registro1402')
data.isnull().sum()

TIPOINGRESO      0
GENERO           0
SEMESTRE         0
ICFES_PUNTAJE    0
ICFES_TIPO       0
DESERTOR         0
CIUDAD           0
ESTRATO_new      0
dtype: int64

In [52]:
data

,TIPOINGRESO,GENERO,SEMESTRE,ICFES_PUNTAJE,ICFES_TIPO,DESERTOR,CIUDAD,ESTRATO_new
0,1.0,0.0,8.0,206.0,4,1,0.0,3.0
1,3.0,0.0,2.0,963.0,4,1,0.0,2.0
2,1.0,1.0,9.0,215.0,1,1,0.0,1.0
3,1.0,1.0,2.0,817.0,4,1,0.0,3.0
4,4.0,1.0,3.0,98.0,4,1,0.0,3.0
...,...,...,...,...,...,...,...,...
254,3.0,1.0,7.0,0.0,4,0,0.0,1.0
255,1.0,1.0,6.0,0.0,4,0,0.0,3.0
256,1.0,1.0,5.0,0.0,4,0,1.0,2.0
257,1.0,1.0,4.0,0.0,4,0,0.0,1.0
258,1.0,1.0,3.0,0.0,4,0,0.0,1.0